# Generated by Django 3.2.16 on 2022-12-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igelmain', '0002_auto_20150511_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='bild',
            field=models.ImageField(upload_to='tutorial'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='kategorie',
            field=models.CharField(choices=[('0', 'Einstieg'), ('1', 'Schleifen'), ('2', 'Funktionen'), ('3', 'Bedingungen'), ('4', 'Für Fortgeschrittene')], max_length=2),
        ),
        migrations.AlterField(
            model_name='beispiel',
            name='bild',
            field=models.ImageField(upload_to='tutorial'),
        ),
        migrations.AlterField(
            model_name='kapitel',
            name='bild',
            field=models.ImageField(upload_to='tutorial'),
        ),
        migrations.AlterField(
            model_name='kapitel',
            name='kategorie',
            field=models.CharField(choices=[('0', 'Einstieg'), ('1', 'Schleifen'), ('2', 'Funktionen'), ('3', 'Bedingungen'), ('4', 'Für Fortgeschrittene')], max_length=2),
        ),
        migrations.AlterField(
            model_name='skript',
            name='bild',
            field=models.ImageField(null=True, upload_to='userskripte'),
        ),
    ]
